#ifndef APP_ENUM_H
#define APP_ENUM_H

#include <QObject>

class App_Enum : public QObject
{
    Q_OBJECT
    Q_ENUMS(OBJECT_INDEX)
    Q_ENUMS(OBJECT_TYPE)
    Q_ENUMS(MULTI_POINTER_MODE)
    Q_ENUMS(E_WIRE_TYPE)
    Q_ENUMS(E_WIRE_STATUS)

public:
    enum OBJECT_INDEX: int{
        E_OBJECT_INDEX_RESISTOR_1 = 0,
        E_OBJECT_INDEX_RESISTOR_2,
        E_OBJECT_INDEX_CAPICTOR_1,
        E_OBJECT_INDEX_CAPICTOR_2,
        E_OBJECT_INDEX_CAPICTOR_3,
        E_OBJECT_INDEX_CONDUTOR_1,
        E_OBJECT_INDEX_CONDUTOR_2,
        E_OBJECT_INDEX_DIODE     ,
        E_OBJECT_INDEX_TRANSISTOR,
        E_OBJECT_INDEX_LED_GREEN,
        E_OBJECT_INDEX_LED_RED,
        E_OBJECT_INDEX_POWER_SOCKET,
        E_OBJECT_INDEX_MULTIMETER,
    };

    enum OBJECT_TYPE: int{
        E_OBJECT_TYPE_RESISTOR = 0,
        E_OBJECT_TYPE_CAPICTOR,
        E_OBJECT_TYPE_CONDUTOR,
        E_OBJECT_TYPE_DIODE,
        E_OBJECT_TYPE_TRANSISTOR,
        E_OBJECT_TYPE_POWER_SOCKET,
        E_OBJECT_TYPE_MULTIMETER,
    };

    enum MULTI_POINTER_MODE: int{
        E_MULTI_POINTER_MODE_OFF     = 0,
        E_MULTI_POINTER_MODE_1000_AC,
        E_MULTI_POINTER_MODE_250_AC,
        E_MULTI_POINTER_MODE_50_AC,
        E_MULTI_POINTER_MODE_10_AC,
        E_MULTI_POINTER_MODE_NA,
        E_MULTI_POINTER_MODE_10K_R,
        E_MULTI_POINTER_MODE_1K_R,
        E_MULTI_POINTER_MODE_10_R,
        E_MULTI_POINTER_MODE_1_R,
        E_MULTI_POINTER_MODE_250_MA,
        E_MULTI_POINTER_MODE_25_MA,
        E_MULTI_POINTER_MODE_2_5_MA,
        E_MULTI_POINTER_MODE_0_1_DC,
        E_MULTI_POINTER_MODE_0_5_DC,
        E_MULTI_POINTER_MODE_2_5_DC,
        E_MULTI_POINTER_MODE_10_DC,
        E_MULTI_POINTER_MODE_50_DC,
        E_MULTI_POINTER_MODE_250_DC,
        E_MULTI_POINTER_MODE_1000_DC,
    };
    enum E_WIRE_TYPE: int{
        E_WIRE_TYPE_NONE = 0,
        E_WIRE_TYPE_RED,
        E_WIRE_TYPE_BLACK,
        E_WIRE_TYPE_FINGER,
    };
    enum E_WIRE_STATUS: int{
        E_WIRE_STATUS_EMPTY,
        E_WIRE_STATUS_FOCUSED,
        E_WIRE_STATUS_CONNECTED,
    };


signals:

public slots:
};

#endif // APP_ENUM_H
